from pathlib import Path


def test_eco_current_capabilities_map_exists_and_contains_required_sections() -> None:
    doc_path = Path("docs/operations/eco-current-capabilities-map.md")
    assert doc_path.exists(), "Debe existir docs/operations/eco-current-capabilities-map.md"

    content = doc_path.read_text(encoding="utf-8")
    lowered = content.lower()

    required_phrases = [
        "pytest passing",
        "dashboard sintético operativo con 8 componentes",
        "governance panel",
        "checklist de liberación",
        "snapshot post-governance",
        "manual de madurez para datos reales biológicos",
        "docs/operations/eco-real-biological-data-maturity-manual.md",
        "capacidad documental de gobernanza",
        "punto de madurez",
        "rechazar, pausar, auditar y explicar",
        "semáforo de madurez",
        "ocho compuertas de madurez",
        "revisión humana",
        "rollback",
        "evidencia auditable",
        "límites interpretativos",
        "no habilita uso de datos reales",
        "no aprueba procesamiento de datos reales por sí mismo",
        "sin datos reales en esta fase",
        "sin diagnóstico",
        "sin interpretación clínica",
        "sin riesgo genético individual",
        "sin afirmaciones biomédicas aplicadas",
        "protocolo de admisión de datos reales biológicos",
        "docs/operations/eco-real-biological-data-admission-protocol.md",
        "docs/operations/eco-real-biological-data-maturity-manual.md",
        "capacidad documental de gobernanza",
        "ruta documental previa",
        "solicitud de admisión",
        "identificación de fuente",
        "clasificación de sensibilidad",
        "revisión de licencia o permiso",
        "revisión técnica previa",
        "revisión ética",
        "revisión interpretativa",
        "revisión humana",
        "decisión registrada",
        "evidencia auditable",
        "rollback",
        "rechazo",
        "compuertas mínimas",
        "estados de decisión permitidos",
        "evidencia mínima requerida",
        "condiciones de rechazo obligatorio",
        "validación técnica limitada",
        "no habilita uso de datos reales",
        "no aprueba procesamiento de datos reales por sí mismo",
        "no reemplaza revisión humana",
        "sin datos reales en esta fase",
        "sin ingestión de datos reales",
        "sin diagnóstico",
        "sin interpretación clínica",
        "sin riesgo genético individual",
        "sin afirmaciones biomédicas aplicadas",
        "demos sintéticas",
        "s.n.e.-e.c.o.",
        "validaciones disponibles",
        "límites responsables",
        "qué no hace todavía e.c.o.",
        "próximo salto recomendado",
        "eco-laos-agency-formula.md",
        "laos",
        "libre albedrío operativo simulado",
        "agencia simulada",
        "autodesarrollo gobernado",
        "no representa libre albedrío real ni conciencia",
        "docs/operations/eco-laos-governance-gate.md",
        "laos governance gate",
        "compuerta de gobernanza",
        "pausar",
        "revisión humana",
        "avanzar con control",
        "sin libre albedrío real",
        "sin conciencia",
        "docs/operations/eco-agentic-scaffold-protocol.md",
        "agentic scaffold protocol",
        "autodesarrollo asistido",
        "agente generativo",
        "plantilla",
        "módulos candidatos",
        "nuevas funciones",
        "sin autonomía real",
        "no implica autonomía real",
        "docs/operations/eco-agentic-scaffold-proposal-template.md",
        "agentic scaffold proposal template",
        "nuevas funciones o módulos candidatos",
        "clasificación inicial",
        "permitido",
        "requiere revisión",
        "bloqueado",
        "archivos mínimos sugeridos",
        "tests contractuales esperados",
        "validaciones requeridas",
        "decisión final humana",
        "docs/operations/eco-agentic-scaffold-proposal-example.md",
        "agentic scaffold proposal example",
        "candidate module: governed operational trace scaffold",
        "ejemplo documental",
        "no ejecutable",
        "pendiente de revisión humana",
        "revisión humana",
        "decisión final humana",
        "no aprueba integración por sí misma",
        "sin autonomía real",
        "sin conciencia",
        "sin libre albedrío real",
        "docs/operations/eco-agentic-scaffold-proposal-registry.md",
        "agentic scaffold proposal registry",
        "catálogo",
        "listado",
        "propuestas agentic scaffold",
        "estado",
        "clasificación",
        "revisión humana",
        "decisión final humana",
        "asc-prop-001",
        "candidate module: governed operational trace scaffold",
        "agentic scaffold proposal registry report",
        "eco-agentic-scaffold-proposal-registry-report",
        "scripts/run_eco_agentic_scaffold_proposal_registry_report.py",
        "results/eco_agentic_scaffold_proposal_registry_report.json",
        "results/eco_agentic_scaffold_proposal_registry_report.md",
        "proposal_count",
        "revisión humana requerida",
        "decisión final humana requerida",
        "solo lectura",
        "no aprueba integración por sí mismo",
        "sin autonomía real",
        "sin conciencia",
        "sin libre albedrío real",
        "sin datos reales",
        "sin entrenamiento",
        "sin modificación de baseline",
        "sin recalibración de umbrales",
        "sin afirmaciones biomédicas aplicadas",
    ]

    for phrase in required_phrases:
        assert phrase in lowered, f"Falta mención requerida: {phrase}"
